// Point to local capacitor-android or node_modules
include ':capacitor-android'
if (new File('./capacitor-android').exists()) {
    project(':capacitor-android').projectDir = new File('./capacitor-android')
} else {
    project(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android/capacitor')
}
